name: test_mobx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.0
  auto_route: ^7.7.1
  infinite_scroll_pagination: ^3.2.0
  get_it: ^8.0.2
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  logger: ^2.5.0
  webp: ^1.0.0+1
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  auto_route_generator: ^7.2.0
  mobx_codegen: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Jaro
      fonts:
        - asset: assets/font/Jaro-Regular-VariableFont_opsz.ttf